llg/urls.py
from django.urls import path

from . import views

app_name = 'llg'
urlpatterns = [
    path('<int:category_pk>', views.index, name='index'),
    path('detail/<int:article_pk>', views.detail, name='detail'),
]

mysite_llg/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("llg/", include("llg.urls")),
    path("home/", views.home, name="home")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

llg/models.py
# -*- coding:utf-8 -*-
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="分类")

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name="标题")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="upload/", null=True, verbose_name="图片")
    content = RichTextField()
    create_datetime = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_datetime = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    def __str__(self):
        return self.title

llg/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Article


# Create your views here.
def index(request, category_pk):
    category = get_object_or_404(Category, pk=category_pk)
    print(category)
    article_list = Article.objects.filter(category=category)
    context = {
        "article_list": article_list
    }
    return render(request, "llg/index.html", context)


def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    context = {
        "article": article
    }
    return render(request, "llg/detail.html", context)

mysite_llg/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request, 'base.html', context)

llg/templates/llg/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-xs-12 col-md-8">
            <img src="{{ article.image.url }}" style="height: auto; width: auto; display: block;margin: 0 auto;">
            <h3>{{ article.title }}</h3>
            <p>{{ article.category }}</p>
            <p>{{ article.content|safe }}</p>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

llg/templates/llg/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2" style="color:#d5d7d8;"></div>
        <div class="col-xs-12 col-md-8">
            <div class="row">
                {% for article in article_list %}
                <div class="col-sm-6 col-md-3">
                    <div class="thumbnail">
                        <div class="image-display">
                            <img src="{{ article.image.url }}" style="height: auto; width: 100%; display: block;">
                        </div>
                        <div class="caption">
                            <h3>标题：<a href="{% url 'llg:detail' article.id%}">{{ article.title }}</a></h3>
                            <p>分类：{{ article.category }}</p>
                            <p><a href="{% url 'llg:detail' article.id%}">
                                {{ article.content|truncatechars:60|safe }}</a>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}



<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    {% block header_extends %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-tabs">
                <li><a href="{% url 'llg:index' 1 %}">古风<span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'llg:index' 2 %}">日系<span class="sr-only">(current)</span></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                <form class="navbar-form">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="查找">
                    </div>
                    <button type="submit" class="btn btn-default">查找</button>
                </form></li>
                <li><a href="#">头像</a></li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}{% endblock %}
{% block script_extends %}{% endblock %}
<div class="footer"></div>
<script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>